#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run Cypress tests in the client
cd client && npm run cy:run

# Run tests in the server (unit tests, e2e tests, etc.)
cd ../server
npm run test
npm run test:e2e
npm run db:dev:restart