name: SERVER

on: [push]

jobs:
  server:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: server
        run: npm install

      - name: Run server tests
        working-directory: server
        run: npm run test

      - name: Push to main branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
